language: java
jobs:
  include:
  - stage: test
    script: ./gradlew test
  - stage: publish
    script: ./gradlew publish -PossrhUsername="${OSSRH_USERNAME}" -PossrhPassword="${OSSRH_PASSWORD}" -Psigning.keyId="${SIGNING_KEY}" -Psigning.password="${SIGNING_PASSWORD}" -Psigning.secretKeyRingFile="`pwd`/javabank.gpg"

stages:
- test
- name: publish
  if: branch = master
before_install:
- openssl aes-256-cbc -K $encrypted_676823bf0942_key -iv $encrypted_676823bf0942_iv
  -in javabank.gpg.enc -out javabank.gpg -d
- gpg --import javabank.gpg
