language: java

script:
- ./gradlew build
- ./gradlew test
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew uploadArchives -PossrhUsername=${OSSRH_USERNAME} -PossrhPassword=${OSSRH_PASSWORD} fi'

