language: java

jobs:
  include:
    - stage: test
      script: ./gradlew clean test
#    - stage: upload
#      script: ./gradlew clean uploadArchives -PossrhUsername=${OSSRH_USERNAME} -PossrhPassword=${OSSRH_PASSWORD}

stages:
  - test
#  - name: upload
#    if: branch = master
